# Make Models

B Steele, Colorado State University, ROSSyndicate — last updated Sep 19, 2026

**Pipeline step 04 · Python · run from `regional_clarity/`**

- **Purpose:** For each of 10 seeds (601–610): correlation pruning, backward elimination, gap-aware tuning, and 4-fold XGBoost training (40 models in all).
- **Inputs:** `aquamatch_files/base_with_splits.parquet`.
- **Outputs:** `xg_models/v3_production/seed{601–610}/`: `backward_elim_summary.json`, `final_tune_xgboost.json`, `xgboost_fold{1–4}.json`, `final_eval_summary.json`, `holdout_predictions.parquet`.
- **Previous:** [03 · Split data](03_split_data.ipynb)
- **Next:** [05 · Evaluate ensemble](05_evaluate_ensemble.ipynb)

This notebook trains the production Secchi-depth model: an ensemble of XGBoost models over ten independent HUC8-random CV arrangements built in `03_split_data.ipynb`, evaluated on that notebook's one fixed, never-trained-on holdout.

**Single algorithm, ten seeds.** An earlier version of this pipeline ensembled 5 seeds × 2 algorithms (XGBoost + LightGBM), for 40 models total. A variance decomposition of that ensemble's holdout predictions found the two algorithms agreed very closely with one another (0.998 correlation between their respective 5-seed ensemble means) while different random seeds disagreed with each other substantially more (~0.99 pairwise correlation); seed choice accounted for roughly 65% of the ensemble's internal prediction spread, versus roughly 13% for model architecture. Given that seed, not algorithm, was the dominant source of useful ensemble variability, this pipeline runs a single algorithm (XGBoost) over 10 independent random seeds instead (`601`–`610`) — 10 seeds × 4 folds = 40 models, the same total model count as the original two-algorithm design, for no measurable accuracy cost and a simpler codebase to maintain.

Each ensemble seed runs its own complete feature-selection + tuning + training pipeline, entirely independently, on its own 4-fold split of the shared CV pool. The final production prediction is the average across all 10 seeds × 4 folds.

## Setup

Import the shared modeling library in `python/`: backward elimination, feature engineering, metrics, the XGBoost wrapper, spatial CV, and gap-aware tuning. Then set the run parameters:

- the 10 ensemble seeds (601–610);
- the number of random-search trials for the initial and final tuning passes (25 and 40);
- the backward-elimination tolerance and seeds;
- the site characteristics and the two curated weather features (`precip_mm_prev30`, `tmax_degC_prev30`) added to the optical candidate pool.

In [1]:
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path("python").resolve()))
import backward_elim as be
import features
import metrics as M
import model_xgb
import spatial_cv
from tuning import gap_aware_tune

be.register_model("xgboost", model_xgb)

AQUAMATCH_DIR = Path("aquamatch_files")
MODELS_DIR = Path("xg_models") / "v3_production"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "harmonized_value"
MODEL_NAME = "xgboost"
MOD = model_xgb
SEEDS = list(range(601, 611))
N_TRIALS_INITIAL = 25
N_TRIALS_FINAL = 40
ELIM_TOL = 0.005
ELIM_SEED = 47
TUNE_SEED = 47

SITE_COLS = ["elevation_m", "catchment_area_sqkm", "pct_impervious_2006", "pct_urban_2006",
             "pct_forest_2006", "pct_cropland_2006", "pct_wetland_2006", "shore_flag"]
WEATHER_COLS_CURATED = ["precip_mm_prev30", "tmax_degC_prev30"]


def log(seed, msg):
    print(f"[{time.strftime('%H:%M:%S')}][seed{seed}] {msg}", flush=True)

## Load data and build 10 fresh CV-fold arrangements

Reads `03_split_data.ipynb`'s output (the same fixed holdout used everywhere else in this project) and adds 10 new `cvfold_seed{601-610}` columns via `spatial_cv.build_splits` — the holdout itself is rebuilt deterministically from the same `holdout_seed=12`, so it comes back identical to `03`'s; only the CV-pool fold arrangement is new. `03`'s legacy `cvfold_seed{501-505}` columns are left untouched alongside these (unused by this pipeline).

`features.coarsen_site_features()` reduces both the *extremity* and the *precision* of `catchment_area_sqkm` (first winsorized at the training-data 99th percentile, then log-scale binned) and rounds the `pct_*_2006` land-cover fractions to the nearest percentage point, so a heavily-resampled or catchment-outlier waterbody's static, per-comid LakeCat values can't act as a de facto waterbody ID for the model to key a memorized SDD value off of. Log-binning alone does this for the ~560 single-HUC8 waterbodies but not for a waterbody with no real neighbors in the distribution - Lake Powell's catchment area (99.5th percentile among waterbodies) stayed cleanly separated from every other large reservoir even after log-binning, and SHAP analysis confirmed the model was leaning on it there specifically. Winsorizing first forces Powell to collide with its nearest real peers (Great Salt Lake, Lake Fort Peck, Flathead Lake, Utah Lake), which measurably reduced that reliance in practice.

In [2]:
df = pd.read_parquet(AQUAMATCH_DIR / "base_with_splits.parquet")
df = features.add_spectral_indices(df)
df = features.coarsen_site_features(df)
df = spatial_cv.build_splits(df, ensemble_seeds=SEEDS)
print(f"{len(df):,} rows, {df.shape[1]} columns; holdout n={df['is_holdout'].sum():,}")

11,143 rows, 72 columns; holdout n=2,206


## Per-seed pipeline (single algorithm)

`run_seed_pipeline()` builds one seed's models from start to finish and saves every artifact to `xg_models/v3_production/seed{seed}/`. All selection decisions use out-of-fold CV only; the fixed holdout is scored only at the end.

1. **Folds.** Build this seed's 4-fold HUC8 arrangement of the CV pool.
2. **Candidate pool and correlation pruning.** Combine the optical features (harmonized bands and spectral indices) with the site characteristics and the curated weather features. Within each cluster of near-duplicate features (|r| > 0.95), keep the one most correlated with SDD.
3. **Initial gap-aware tuning.** Run a 25-trial random hyperparameter search. Among the trials whose mean validation RMSE is within 2% of the best, choose the one with the smallest train–validation gap. These hyperparameters are held fixed during elimination. Each seed uses its own search seed (`TUNE_SEED + seed`), so the 10 seeds explore different parts of hyperparameter space.
4. **Backward elimination with shadow decoys.** Each real feature gets a row-permuted "shadow" copy that has no relationship to SDD. At each step, drop the weakest real feature if its permutation importance does not beat the shadows. Stop when every remaining feature beats the shadows, or when mean CV RMSE degrades by more than `ELIM_TOL` relative to the best point on the path. The survivors form the seed's final feature set.
5. **Final gap-aware tuning.** Re-run the tuning procedure on the final feature set with 40 trials.
6. **Final training and evaluation.** Train the four fold models, then score them on their own validation folds (CV) and as a 4-model average on the fixed holdout. Save the fold models, the feature and hyperparameter configurations, the metrics, and the holdout predictions.

In [3]:
def run_seed_pipeline(seed, df):
    out_dir = MODELS_DIR / f"seed{seed}"
    out_dir.mkdir(parents=True, exist_ok=True)
    t_start = time.time()

    folds = spatial_cv.build_folds(df, seed)
    test = df[df["is_holdout"]].reset_index(drop=True)
    log(seed, f"folds: {[(f.part, len(f.train), len(f.val)) for f in folds]}, holdout n={len(test)}")

    # --- candidate pool + correlation pruning (this seed's own train_val pool) ---
    metadata_cols = {"HUC8", "holdout_part", "is_holdout"} | {f"cvfold_seed{s}" for s in SEEDS}
    extra_cols = set(SITE_COLS) | set(WEATHER_COLS_CURATED) | metadata_cols
    optical_feats = [f for f in features.candidate_feature_list(df) if f not in extra_cols]
    candidates = optical_feats + SITE_COLS + WEATHER_COLS_CURATED

    train_val = pd.concat([f.train for f in folds] + [folds[0].val], ignore_index=True).drop_duplicates(
        subset=["siteSR_id", "date"])
    pruned = features.correlation_prune(train_val, candidates, target=TARGET)
    log(seed, f"candidate pool: {len(candidates)} -> {len(pruned)} after correlation pruning")

    # tuning seed is derived per-ensemble-seed (rather than a single fixed value shared
    # by every seed) so each seed's random search explores a genuinely different draw of
    # hyperparameter combinations - previously every seed reused seed=47 verbatim, so all
    # 10 seeds evaluated the identical set of combinations against their own data instead
    # of diversifying search coverage across the ensemble the way the CV folds and feature
    # selection already do
    seed_tune_seed = TUNE_SEED + seed

    # --- stage 1: initial gap-aware tuning (fixed params for elimination) ---
    log(seed, f"=== initial gap-aware tuning on {len(pruned)}-feature pool ===")
    init_result = gap_aware_tune(MOD, folds, pruned, TARGET, n_trials=N_TRIALS_INITIAL, seed=seed_tune_seed)
    fixed_params = init_result["best_params"]
    log(seed, f"val_rmse={init_result['best_score']:.4f} gap={init_result['best_gap']:.4f}")

    # --- stage 2: backward elimination (single algorithm, no joint step) ---
    log(seed, "=== backward elimination ===")
    elim_result = be.backward_eliminate(MODEL_NAME, folds, TARGET, fixed_params, pruned,
                                        weight_fn=None, tol=ELIM_TOL, seed=ELIM_SEED,
                                        log=lambda m: log(seed, m))
    final_feats = elim_result["final_features"]
    log(seed, f"final ({len(final_feats)}): {final_feats}")

    with open(out_dir / "backward_elim_summary.json", "w") as fh:
        json.dump(dict(starting_candidates=candidates, correlation_pruned=pruned,
                       final_features=final_feats, path=elim_result["path"]), fh, indent=2, default=str)

    # --- stage 3: final gap-aware tuning on the final feature set ---
    log(seed, f"=== final gap-aware tuning on {len(final_feats)}-feature set ===")
    tune_result = gap_aware_tune(MOD, folds, final_feats, TARGET, n_trials=N_TRIALS_FINAL, seed=seed_tune_seed)
    log(seed, f"chosen: val_rmse={tune_result['best_score']:.4f} gap={tune_result['best_gap']:.4f}")
    with open(out_dir / f"final_tune_{MODEL_NAME}.json", "w") as fh:
        json.dump({"model": MODEL_NAME, "features": final_feats, **tune_result}, fh, indent=2, default=str)

    # --- stage 4: final unweighted training + evaluation ---
    params = tune_result["best_params"]
    fold_models = MOD.train_fold_models(folds, final_feats, TARGET, params)
    for i, fm in enumerate(fold_models):
        fm.save_model(str(out_dir / f"{MODEL_NAME}_fold{i+1}.json"))

    cv_preds, cv_ys = [], []
    for f, model in zip(folds, fold_models):
        cv_preds.append(MOD.predict_ensemble([model], f.val[final_feats]))
        cv_ys.append(f.val[TARGET].values)
    cv_metrics = M.all_metrics(np.concatenate(cv_ys), np.concatenate(cv_preds))

    test_pred = MOD.predict_ensemble(fold_models, test[final_feats])
    test_metrics = M.all_metrics(test[TARGET].values, test_pred)
    log(seed, f"FINAL: cv_rmse={cv_metrics['rmse']:.4f} holdout_rmse={test_metrics['rmse']:.4f}")

    summary = {MODEL_NAME: dict(features=final_feats, params=params, cv_metrics=cv_metrics, test_metrics=test_metrics)}
    with open(out_dir / "final_eval_summary.json", "w") as fh:
        json.dump(summary, fh, indent=2, default=str)

    r = test[["siteSR_id", "date", "HUC4", "HUC8"]].copy()
    r["seed"] = seed
    r["model"] = MODEL_NAME
    r["y"] = test[TARGET].values
    r["pred"] = test_pred
    r.to_parquet(out_dir / "holdout_predictions.parquet")

    log(seed, f"SEED {seed} DONE in {time.time()-t_start:.0f}s")
    return summary

Run the pipeline for all 10 seeds. Each seed is independent, so the CV arrangement, selected features, and hyperparameters can all differ from seed to seed.

In [4]:
all_summaries = {}
for seed in SEEDS:
    all_summaries[seed] = run_seed_pipeline(seed, df)

[11:02:46][seed601] folds: [(1, 6764, 2173), (2, 6551, 2386), (3, 6822, 2115), (4, 6674, 2263)], holdout n=2206


[11:02:46][seed601] candidate pool: 45 -> 34 after correlation pruning


[11:02:46][seed601] === initial gap-aware tuning on 34-feature pool ===


[11:04:46][seed601] val_rmse=1.4969 gap=0.5039


[11:04:46][seed601] === backward elimination ===


[11:05:20][seed601]   [xgboost] step 0: n=34 cv_rmse=1.5162 shadow_floor=0.0004


[11:05:20][seed601]   [xgboost] drop 'elevation_m' (importance -0.0047 <= shadow floor 0.0004)


[11:05:56][seed601]   [xgboost] step 1: n=33 cv_rmse=1.5009 shadow_floor=0.0002


[11:05:56][seed601]   [xgboost] drop 'precip_mm_prev3' (importance -0.0025 <= shadow floor 0.0002)


[11:06:39][seed601]   [xgboost] step 2: n=32 cv_rmse=1.4949 shadow_floor=0.0004


[11:06:39][seed601]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0020 <= shadow floor 0.0004)


[11:07:19][seed601]   [xgboost] step 3: n=31 cv_rmse=1.4965 shadow_floor=0.0006


[11:07:19][seed601]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0012 <= shadow floor 0.0006)


[11:08:00][seed601]   [xgboost] step 4: n=30 cv_rmse=1.4919 shadow_floor=0.0005


[11:08:00][seed601]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0020 <= shadow floor 0.0005)


[11:08:45][seed601]   [xgboost] step 5: n=29 cv_rmse=1.4924 shadow_floor=0.0004


[11:08:45][seed601]   [xgboost] drop 'precip_mm_prev30' (importance -0.0012 <= shadow floor 0.0004)


[11:09:29][seed601]   [xgboost] step 6: n=28 cv_rmse=1.4895 shadow_floor=0.0005


[11:09:29][seed601]   [xgboost] drop 'pct_urban_2006' (importance -0.0044 <= shadow floor 0.0005)


[11:10:07][seed601]   [xgboost] step 7: n=27 cv_rmse=1.4720 shadow_floor=0.0004


[11:10:07][seed601]   [xgboost] drop 'precip_mm_prev7' (importance -0.0014 <= shadow floor 0.0004)


[11:10:46][seed601]   [xgboost] step 8: n=26 cv_rmse=1.4675 shadow_floor=0.0007


[11:10:46][seed601]   [xgboost] stop: worst real feature 'precip_mm_prev1' (0.0012) beats shadow floor (0.0007)


[11:10:46][seed601] final (26): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[11:10:46][seed601] === final gap-aware tuning on 26-feature set ===


[11:14:59][seed601] chosen: val_rmse=1.4539 gap=0.4736


[11:15:10][seed601] FINAL: cv_rmse=1.4667 holdout_rmse=1.2708


[11:15:10][seed601] SEED 601 DONE in 744s


[11:15:10][seed602] folds: [(1, 6819, 2118), (2, 6744, 2193), (3, 6788, 2149), (4, 6460, 2477)], holdout n=2206


[11:15:10][seed602] candidate pool: 45 -> 34 after correlation pruning


[11:15:10][seed602] === initial gap-aware tuning on 34-feature pool ===


[11:16:58][seed602] val_rmse=1.4725 gap=0.3739


[11:16:58][seed602] === backward elimination ===


[11:17:34][seed602]   [xgboost] step 0: n=34 cv_rmse=1.4765 shadow_floor=0.0003


[11:17:34][seed602]   [xgboost] drop 'elevation_m' (importance -0.0077 <= shadow floor 0.0003)


[11:18:12][seed602]   [xgboost] step 1: n=33 cv_rmse=1.4600 shadow_floor=0.0005


[11:18:12][seed602]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0027 <= shadow floor 0.0005)


[11:18:47][seed602]   [xgboost] step 2: n=32 cv_rmse=1.4580 shadow_floor=0.0003


[11:18:47][seed602]   [xgboost] drop 'precip_mm_prev7' (importance -0.0021 <= shadow floor 0.0003)


[11:19:16][seed602]   [xgboost] step 3: n=31 cv_rmse=1.4647 shadow_floor=0.0003


[11:19:16][seed602]   [xgboost] drop 'precip_mm_prev30' (importance -0.0009 <= shadow floor 0.0003)


[11:19:53][seed602]   [xgboost] step 4: n=30 cv_rmse=1.4549 shadow_floor=0.0005


[11:19:53][seed602]   [xgboost] drop 'tmin_degC_prev30' (importance 0.0003 <= shadow floor 0.0005)


[11:20:27][seed602]   [xgboost] step 5: n=29 cv_rmse=1.4487 shadow_floor=0.0005


[11:20:27][seed602]   [xgboost] drop 'precip_mm_prev1' (importance -0.0001 <= shadow floor 0.0005)


[11:20:57][seed602]   [xgboost] step 6: n=28 cv_rmse=1.4524 shadow_floor=0.0005


[11:20:57][seed602]   [xgboost] stop: worst real feature 'NDWI' (0.0009) beats shadow floor (0.0005)


[11:20:57][seed602] final (29): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'precip_mm_prev3', 'srad_Wm2_prev7', 'tmax_degC_prev7', 'tmean_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[11:20:57][seed602] === final gap-aware tuning on 29-feature set ===


[11:24:07][seed602] chosen: val_rmse=1.4530 gap=0.3636


[11:24:14][seed602] FINAL: cv_rmse=1.4764 holdout_rmse=1.2798


[11:24:14][seed602] SEED 602 DONE in 544s


[11:24:14][seed603] folds: [(1, 6629, 2308), (2, 6619, 2318), (3, 6760, 2177), (4, 6803, 2134)], holdout n=2206


[11:24:14][seed603] candidate pool: 45 -> 34 after correlation pruning


[11:24:14][seed603] === initial gap-aware tuning on 34-feature pool ===


[11:25:44][seed603] val_rmse=1.5032 gap=0.5106


[11:25:44][seed603] === backward elimination ===


[11:25:59][seed603]   [xgboost] step 0: n=34 cv_rmse=1.5217 shadow_floor=0.0003


[11:25:59][seed603]   [xgboost] drop 'elevation_m' (importance -0.0062 <= shadow floor 0.0003)


[11:26:17][seed603]   [xgboost] step 1: n=33 cv_rmse=1.4883 shadow_floor=0.0004


[11:26:17][seed603]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0030 <= shadow floor 0.0004)


[11:26:35][seed603]   [xgboost] step 2: n=32 cv_rmse=1.4905 shadow_floor=0.0005


[11:26:35][seed603]   [xgboost] drop 'precip_mm_prev3' (importance -0.0029 <= shadow floor 0.0005)


[11:26:52][seed603]   [xgboost] step 3: n=31 cv_rmse=1.4961 shadow_floor=0.0003


[11:26:52][seed603]   [xgboost] stop: cv_rmse degraded >0.5% from best (1.4883)


[11:26:52][seed603] final (33): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'precip_mm_prev3', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'precip_mm_prev30', 'tmax_degC_prev30']


[11:26:52][seed603] === final gap-aware tuning on 33-feature set ===


[11:29:04][seed603] chosen: val_rmse=1.4763 gap=0.4536


[11:29:07][seed603] FINAL: cv_rmse=1.5257 holdout_rmse=1.2722


[11:29:07][seed603] SEED 603 DONE in 293s


[11:29:07][seed604] folds: [(1, 6521, 2416), (2, 6875, 2062), (3, 6657, 2280), (4, 6758, 2179)], holdout n=2206


[11:29:07][seed604] candidate pool: 45 -> 34 after correlation pruning


[11:29:07][seed604] === initial gap-aware tuning on 34-feature pool ===


[11:31:28][seed604] val_rmse=1.4445 gap=0.5049


[11:31:28][seed604] === backward elimination ===


[11:31:46][seed604]   [xgboost] step 0: n=34 cv_rmse=1.4531 shadow_floor=0.0007


[11:31:46][seed604]   [xgboost] drop 'elevation_m' (importance -0.0080 <= shadow floor 0.0007)


[11:32:06][seed604]   [xgboost] step 1: n=33 cv_rmse=1.4315 shadow_floor=0.0005


[11:32:06][seed604]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0045 <= shadow floor 0.0005)


[11:32:23][seed604]   [xgboost] step 2: n=32 cv_rmse=1.4267 shadow_floor=0.0006


[11:32:23][seed604]   [xgboost] drop 'precip_mm_prev3' (importance -0.0019 <= shadow floor 0.0006)


[11:32:40][seed604]   [xgboost] step 3: n=31 cv_rmse=1.4280 shadow_floor=0.0007


[11:32:40][seed604]   [xgboost] drop 'precip_mm_prev30' (importance -0.0019 <= shadow floor 0.0007)


[11:32:57][seed604]   [xgboost] step 4: n=30 cv_rmse=1.4323 shadow_floor=0.0006


[11:32:57][seed604]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0012 <= shadow floor 0.0006)


[11:33:17][seed604]   [xgboost] step 5: n=29 cv_rmse=1.4203 shadow_floor=0.0006


[11:33:17][seed604]   [xgboost] drop 'precip_mm_prev1' (importance 0.0005 <= shadow floor 0.0006)


[11:33:36][seed604]   [xgboost] step 6: n=28 cv_rmse=1.4080 shadow_floor=0.0006


[11:33:36][seed604]   [xgboost] stop: worst real feature 'swir1_corr7' (0.0018) beats shadow floor (0.0006)


[11:33:36][seed604] final (28): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[11:33:36][seed604] === final gap-aware tuning on 28-feature set ===


[11:37:40][seed604] chosen: val_rmse=1.3956 gap=0.4456


[11:37:50][seed604] FINAL: cv_rmse=1.4359 holdout_rmse=1.2751


[11:37:50][seed604] SEED 604 DONE in 523s


[11:37:50][seed605] folds: [(1, 6520, 2417), (2, 6909, 2028), (3, 6497, 2440), (4, 6885, 2052)], holdout n=2206


[11:37:50][seed605] candidate pool: 45 -> 34 after correlation pruning


[11:37:50][seed605] === initial gap-aware tuning on 34-feature pool ===


[11:39:51][seed605] val_rmse=1.4765 gap=0.4693


[11:39:51][seed605] === backward elimination ===


[11:40:35][seed605]   [xgboost] step 0: n=34 cv_rmse=1.4852 shadow_floor=0.0006


[11:40:35][seed605]   [xgboost] drop 'elevation_m' (importance -0.0069 <= shadow floor 0.0006)


[11:41:19][seed605]   [xgboost] step 1: n=33 cv_rmse=1.4658 shadow_floor=0.0005


[11:41:19][seed605]   [xgboost] drop 'precip_mm_prev30' (importance -0.0033 <= shadow floor 0.0005)


[11:42:00][seed605]   [xgboost] step 2: n=32 cv_rmse=1.4684 shadow_floor=0.0010


[11:42:00][seed605]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0029 <= shadow floor 0.0010)


[11:42:43][seed605]   [xgboost] step 3: n=31 cv_rmse=1.4632 shadow_floor=0.0004


[11:42:43][seed605]   [xgboost] drop 'precip_mm_prev7' (importance -0.0033 <= shadow floor 0.0004)


[11:43:23][seed605]   [xgboost] step 4: n=30 cv_rmse=1.4642 shadow_floor=0.0005


[11:43:23][seed605]   [xgboost] drop 'precip_mm_prev3' (importance -0.0022 <= shadow floor 0.0005)


[11:44:00][seed605]   [xgboost] step 5: n=29 cv_rmse=1.4577 shadow_floor=0.0003


[11:44:00][seed605]   [xgboost] drop 'swir1_corr7' (importance -0.0004 <= shadow floor 0.0003)


[11:44:42][seed605]   [xgboost] step 6: n=28 cv_rmse=1.4551 shadow_floor=0.0006


[11:44:42][seed605]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0009 <= shadow floor 0.0006)


[11:45:19][seed605]   [xgboost] step 7: n=27 cv_rmse=1.4551 shadow_floor=0.0007


[11:45:19][seed605]   [xgboost] drop 'tmean_degC_prev7' (importance 0.0004 <= shadow floor 0.0007)


[11:45:53][seed605]   [xgboost] step 8: n=26 cv_rmse=1.4543 shadow_floor=0.0006


[11:45:53][seed605]   [xgboost] stop: worst real feature 'srad_Wm2_prev7' (0.0010) beats shadow floor (0.0006)


[11:45:53][seed605] final (26): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'temp_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[11:45:53][seed605] === final gap-aware tuning on 26-feature set ===


[11:49:07][seed605] chosen: val_rmse=1.4405 gap=0.4172


[11:49:09][seed605] FINAL: cv_rmse=1.4452 holdout_rmse=1.2668


[11:49:09][seed605] SEED 605 DONE in 679s


[11:49:09][seed606] folds: [(1, 6605, 2332), (2, 6842, 2095), (3, 6834, 2103), (4, 6530, 2407)], holdout n=2206


[11:49:09][seed606] candidate pool: 45 -> 34 after correlation pruning


[11:49:09][seed606] === initial gap-aware tuning on 34-feature pool ===


[11:50:45][seed606] val_rmse=1.4199 gap=0.4400


[11:50:45][seed606] === backward elimination ===


[11:51:20][seed606]   [xgboost] step 0: n=34 cv_rmse=1.4305 shadow_floor=0.0003


[11:51:20][seed606]   [xgboost] drop 'precip_mm_prev7' (importance -0.0018 <= shadow floor 0.0003)


[11:51:54][seed606]   [xgboost] step 1: n=33 cv_rmse=1.4225 shadow_floor=0.0002


[11:51:54][seed606]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0016 <= shadow floor 0.0002)


[11:52:27][seed606]   [xgboost] step 2: n=32 cv_rmse=1.4323 shadow_floor=0.0003


[11:52:27][seed606]   [xgboost] stop: cv_rmse degraded >0.5% from best (1.4225)


[11:52:27][seed606] final (33): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'precip_mm_prev3', 'srad_Wm2_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'precip_mm_prev30', 'tmax_degC_prev30']


[11:52:27][seed606] === final gap-aware tuning on 33-feature set ===


[11:55:02][seed606] chosen: val_rmse=1.4394 gap=0.3841


[11:55:04][seed606] FINAL: cv_rmse=1.4960 holdout_rmse=1.2736


[11:55:04][seed606] SEED 606 DONE in 355s


[11:55:04][seed607] folds: [(1, 6713, 2224), (2, 6841, 2096), (3, 6399, 2538), (4, 6858, 2079)], holdout n=2206


[11:55:04][seed607] candidate pool: 45 -> 34 after correlation pruning


[11:55:04][seed607] === initial gap-aware tuning on 34-feature pool ===


[11:57:00][seed607] val_rmse=1.4127 gap=0.5283


[11:57:00][seed607] === backward elimination ===


[11:57:14][seed607]   [xgboost] step 0: n=34 cv_rmse=1.4438 shadow_floor=0.0006


[11:57:14][seed607]   [xgboost] drop 'elevation_m' (importance -0.0044 <= shadow floor 0.0006)


[11:57:26][seed607]   [xgboost] step 1: n=33 cv_rmse=1.4396 shadow_floor=0.0006


[11:57:26][seed607]   [xgboost] drop 'precip_mm_prev30' (importance -0.0016 <= shadow floor 0.0006)


[11:57:37][seed607]   [xgboost] step 2: n=32 cv_rmse=1.4372 shadow_floor=0.0006


[11:57:37][seed607]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0026 <= shadow floor 0.0006)


[11:57:48][seed607]   [xgboost] step 3: n=31 cv_rmse=1.4274 shadow_floor=0.0004


[11:57:48][seed607]   [xgboost] drop 'pct_cropland_2006' (importance -0.0021 <= shadow floor 0.0004)


[11:57:59][seed607]   [xgboost] step 4: n=30 cv_rmse=1.4172 shadow_floor=0.0006


[11:57:59][seed607]   [xgboost] drop 'precip_mm_prev1' (importance -0.0009 <= shadow floor 0.0006)


[11:58:11][seed607]   [xgboost] step 5: n=29 cv_rmse=1.4124 shadow_floor=0.0006


[11:58:11][seed607]   [xgboost] drop 'precip_mm_prev3' (importance -0.0009 <= shadow floor 0.0006)


[11:58:22][seed607]   [xgboost] step 6: n=28 cv_rmse=1.4184 shadow_floor=0.0006


[11:58:22][seed607]   [xgboost] drop 'precip_mm_prev7' (importance 0.0002 <= shadow floor 0.0006)


[11:58:33][seed607]   [xgboost] step 7: n=27 cv_rmse=1.4096 shadow_floor=0.0009


[11:58:33][seed607]   [xgboost] stop: worst real feature 'srad_Wm2_prev7' (0.0014) beats shadow floor (0.0009)


[11:58:33][seed607] final (27): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[11:58:33][seed607] === final gap-aware tuning on 27-feature set ===


[12:01:20][seed607] chosen: val_rmse=1.4155 gap=0.4390


[12:01:23][seed607] FINAL: cv_rmse=1.4564 holdout_rmse=1.2757


[12:01:23][seed607] SEED 607 DONE in 378s


[12:01:23][seed608] folds: [(1, 6772, 2165), (2, 6808, 2129), (3, 6575, 2362), (4, 6656, 2281)], holdout n=2206


[12:01:23][seed608] candidate pool: 45 -> 34 after correlation pruning


[12:01:23][seed608] === initial gap-aware tuning on 34-feature pool ===


[12:03:22][seed608] val_rmse=1.4548 gap=0.4099


[12:03:22][seed608] === backward elimination ===


[12:03:50][seed608]   [xgboost] step 0: n=34 cv_rmse=1.4729 shadow_floor=0.0002


[12:03:50][seed608]   [xgboost] drop 'precip_mm_prev3' (importance -0.0038 <= shadow floor 0.0002)


[12:04:21][seed608]   [xgboost] step 1: n=33 cv_rmse=1.4629 shadow_floor=0.0004


[12:04:21][seed608]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0024 <= shadow floor 0.0004)


[12:04:51][seed608]   [xgboost] step 2: n=32 cv_rmse=1.4620 shadow_floor=0.0004


[12:04:51][seed608]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0009 <= shadow floor 0.0004)


[12:05:23][seed608]   [xgboost] step 3: n=31 cv_rmse=1.4582 shadow_floor=0.0004


[12:05:23][seed608]   [xgboost] drop 'precip_mm_prev7' (importance -0.0016 <= shadow floor 0.0004)


[12:05:53][seed608]   [xgboost] step 4: n=30 cv_rmse=1.4622 shadow_floor=0.0003


[12:05:53][seed608]   [xgboost] drop 'precip_mm_prev30' (importance -0.0005 <= shadow floor 0.0003)


[12:06:22][seed608]   [xgboost] step 5: n=29 cv_rmse=1.4565 shadow_floor=0.0003


[12:06:22][seed608]   [xgboost] drop 'tmean_degC_prev7' (importance 0.0003 <= shadow floor 0.0003)


[12:06:51][seed608]   [xgboost] step 6: n=28 cv_rmse=1.4564 shadow_floor=0.0004


[12:06:51][seed608]   [xgboost] drop 'precip_mm_prev1' (importance 0.0002 <= shadow floor 0.0004)


[12:07:23][seed608]   [xgboost] step 7: n=27 cv_rmse=1.4571 shadow_floor=0.0004


[12:07:23][seed608]   [xgboost] drop 'swir1_corr7' (importance -0.0000 <= shadow floor 0.0004)


[12:07:51][seed608]   [xgboost] step 8: n=26 cv_rmse=1.4615 shadow_floor=0.0004


[12:07:51][seed608]   [xgboost] stop: worst real feature 'NDWI' (0.0014) beats shadow floor (0.0004)


[12:07:51][seed608] final (28): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[12:07:51][seed608] === final gap-aware tuning on 28-feature set ===


[12:10:58][seed608] chosen: val_rmse=1.4391 gap=0.3739


[12:11:00][seed608] FINAL: cv_rmse=1.4502 holdout_rmse=1.2576


[12:11:00][seed608] SEED 608 DONE in 577s


[12:11:00][seed609] folds: [(1, 6798, 2139), (2, 6560, 2377), (3, 6801, 2136), (4, 6652, 2285)], holdout n=2206


[12:11:00][seed609] candidate pool: 45 -> 34 after correlation pruning


[12:11:00][seed609] === initial gap-aware tuning on 34-feature pool ===


[12:12:18][seed609] val_rmse=1.4917 gap=0.3375


[12:12:18][seed609] === backward elimination ===


[12:12:44][seed609]   [xgboost] step 0: n=34 cv_rmse=1.4954 shadow_floor=0.0004


[12:12:44][seed609]   [xgboost] drop 'elevation_m' (importance -0.0046 <= shadow floor 0.0004)


[12:13:08][seed609]   [xgboost] step 1: n=33 cv_rmse=1.4809 shadow_floor=0.0002


[12:13:08][seed609]   [xgboost] drop 'precip_mm_prev30' (importance -0.0010 <= shadow floor 0.0002)


[12:13:32][seed609]   [xgboost] step 2: n=32 cv_rmse=1.4856 shadow_floor=0.0004


[12:13:32][seed609]   [xgboost] drop 'precip_mm_prev7' (importance -0.0011 <= shadow floor 0.0004)


[12:13:54][seed609]   [xgboost] step 3: n=31 cv_rmse=1.4855 shadow_floor=0.0001


[12:13:54][seed609]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0004 <= shadow floor 0.0001)


[12:14:17][seed609]   [xgboost] step 4: n=30 cv_rmse=1.4818 shadow_floor=0.0003


[12:14:17][seed609]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0004 <= shadow floor 0.0003)


[12:14:42][seed609]   [xgboost] step 5: n=29 cv_rmse=1.4847 shadow_floor=0.0003


[12:14:42][seed609]   [xgboost] drop 'precip_mm_prev3' (importance -0.0002 <= shadow floor 0.0003)


[12:15:05][seed609]   [xgboost] step 6: n=28 cv_rmse=1.4852 shadow_floor=0.0002


[12:15:05][seed609]   [xgboost] drop 'tmin_degC_prev30' (importance 0.0001 <= shadow floor 0.0002)


[12:15:29][seed609]   [xgboost] step 7: n=27 cv_rmse=1.4811 shadow_floor=0.0002


[12:15:29][seed609]   [xgboost] drop 'swir1_corr7' (importance -0.0003 <= shadow floor 0.0002)


[12:15:51][seed609]   [xgboost] step 8: n=26 cv_rmse=1.4823 shadow_floor=0.0003


[12:15:51][seed609]   [xgboost] stop: worst real feature 'tmin_degC_prev7' (0.0007) beats shadow floor (0.0003)


[12:15:51][seed609] final (33): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'precip_mm_prev3', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'precip_mm_prev30', 'tmax_degC_prev30']


[12:15:51][seed609] === final gap-aware tuning on 33-feature set ===


[12:17:54][seed609] chosen: val_rmse=1.4627 gap=0.3990


[12:17:58][seed609] FINAL: cv_rmse=1.4642 holdout_rmse=1.2674


[12:17:58][seed609] SEED 609 DONE in 418s


[12:17:58][seed610] folds: [(1, 6737, 2200), (2, 6759, 2178), (3, 6637, 2300), (4, 6678, 2259)], holdout n=2206


[12:17:58][seed610] candidate pool: 45 -> 34 after correlation pruning


[12:17:58][seed610] === initial gap-aware tuning on 34-feature pool ===


[12:19:33][seed610] val_rmse=1.4842 gap=0.4573


[12:19:33][seed610] === backward elimination ===


[12:19:45][seed610]   [xgboost] step 0: n=34 cv_rmse=1.4869 shadow_floor=0.0004


[12:19:45][seed610]   [xgboost] drop 'elevation_m' (importance -0.0048 <= shadow floor 0.0004)


[12:20:00][seed610]   [xgboost] step 1: n=33 cv_rmse=1.4654 shadow_floor=0.0006


[12:20:00][seed610]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0018 <= shadow floor 0.0006)


[12:20:13][seed610]   [xgboost] step 2: n=32 cv_rmse=1.4577 shadow_floor=0.0005


[12:20:13][seed610]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0014 <= shadow floor 0.0005)


[12:20:28][seed610]   [xgboost] step 3: n=31 cv_rmse=1.4545 shadow_floor=0.0004


[12:20:28][seed610]   [xgboost] drop 'precip_mm_prev30' (importance -0.0020 <= shadow floor 0.0004)


[12:20:42][seed610]   [xgboost] step 4: n=30 cv_rmse=1.4479 shadow_floor=0.0006


[12:20:42][seed610]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0020 <= shadow floor 0.0006)


[12:20:55][seed610]   [xgboost] step 5: n=29 cv_rmse=1.4548 shadow_floor=0.0005


[12:20:55][seed610]   [xgboost] drop 'precip_mm_prev3' (importance 0.0000 <= shadow floor 0.0005)


[12:21:09][seed610]   [xgboost] step 6: n=28 cv_rmse=1.4506 shadow_floor=0.0009


[12:21:09][seed610]   [xgboost] drop 'precip_mm_prev1' (importance 0.0003 <= shadow floor 0.0009)


[12:21:22][seed610]   [xgboost] step 7: n=27 cv_rmse=1.4355 shadow_floor=0.0007


[12:21:22][seed610]   [xgboost] drop 'precip_mm_prev7' (importance 0.0007 <= shadow floor 0.0007)


[12:21:33][seed610]   [xgboost] step 8: n=26 cv_rmse=1.4490 shadow_floor=0.0012


[12:21:33][seed610]   [xgboost] stop: cv_rmse degraded >0.5% from best (1.4355)


[12:21:33][seed610] final (27): ['atm_corr_LaSRC', 'green_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[12:21:33][seed610] === final gap-aware tuning on 27-feature set ===


[12:24:23][seed610] chosen: val_rmse=1.4504 gap=0.5321


[12:24:27][seed610] FINAL: cv_rmse=1.4541 holdout_rmse=1.2682


[12:24:27][seed610] SEED 610 DONE in 389s


## Per-seed summary

One row per seed: the size of its final feature set, its out-of-fold CV RMSE, and its own 4-model holdout RMSE and bias. Seeds that differ widely here would suggest the result depends heavily on the CV arrangement.

In [5]:
rows = []
for seed, summary in all_summaries.items():
    s = summary[MODEL_NAME]
    rows.append(dict(seed=seed, n_features=len(s["features"]), cv_rmse=s["cv_metrics"]["rmse"],
                     holdout_rmse=s["test_metrics"]["rmse"], holdout_bias=s["test_metrics"]["bias"]))
pd.DataFrame(rows).sort_values("seed")

,seed,n_features,cv_rmse,holdout_rmse,holdout_bias
0,601,26,1.466661,1.270780,0.182161
1,602,29,1.476379,1.279810,0.200973
2,603,33,1.525656,1.272230,0.160546
3,604,28,1.435883,1.275089,0.183181
4,605,26,1.445207,1.266821,0.180986
5,606,33,1.495951,1.273629,0.150936
6,607,27,1.456433,1.275716,0.173353
7,608,28,1.450193,1.257611,0.192081
8,609,33,1.464244,1.267364,0.195231
9,610,27,1.454059,1.268166,0.175679


## Assemble the 10-seed ensemble

40 models (10 seeds x 4 folds). Full evaluation (HUC8 breakdown, seed-vs-seed spread, SHAP) happens in `05_evaluate_ensemble.ipynb`; this is a quick sanity check on the assembled holdout metrics before moving on.

In [6]:
rows = []
for seed in SEEDS:
    rows.append(pd.read_parquet(MODELS_DIR / f"seed{seed}" / "holdout_predictions.parquet"))
all_preds = pd.concat(rows, ignore_index=True)

ensemble_pred = all_preds.groupby(["siteSR_id", "date"]).agg(y=("y", "first"), pred=("pred", "mean")).reset_index()
ensemble_metrics = M.all_metrics(ensemble_pred["y"], ensemble_pred["pred"])
print(f"production ensemble (10 seeds x xgboost, 40 models): {ensemble_metrics}")

production ensemble (10 seeds x xgboost, 40 models): {'rmse': 1.2566756728290513, 'mae': 0.9405392672660504, 'mape': 0.41856974124174623, 'bias': 0.15237427796422623, 'p_bias': 4.724044610153776, 'smape': 0.3181520832907615, 'r2': 0.6274223196403295, 'n': 1833}


## Summary

The production model is a 40-member ensemble — 10 independent HUC8-random CV arrangements x 4 folds each — trained unweighted, with gap-aware hyperparameter selection at every tuning stage and per-seed feature sets chosen by correlation pruning followed by shadow-decoy backward elimination. Every member is evaluated on one fixed HUC8-random holdout that no model ever trains on. Artifacts (fold models, per-seed feature/hyperparameter configs, holdout predictions) are saved under `xg_models/v3_production/seed{601–610}/`. See `05_evaluate_ensemble.ipynb` for the full evaluation (HUC8 breakdown, seed-vs-seed spread, SHAP).